baseURL = "http://hiromi.eu.org/"
languageCode = "zh-cn"
title = "Hiromi的藏书处"
theme = "pixlike"
hasCJKLanguage = true

[params]
    author = "Hiromi"
    description = ""

[taxonomies]
    series = "series"
    tag = "tags"
    category = "categories"
